# Generated by Django 2.2.19 on 2021-03-24 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artistgraph', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='index',
        ),
    ]
